plugins {
    id 'java'
}

group = 'org.senix'
version = 'DEVELOP-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly(files('libs/HytaleServer.jar'))
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from("src/main/resources")
}